## **FAIZAL RIZA**
### akuisal@gmail.com
### cohort id : L144YWD051

# **Penting**
- Jangan mengubah atau menambahkan cell text yang sudah disediakan, Anda hanya perlu mengerjakan cell code yang sudah disediakan.
- Pastikan seluruh kriteria memiliki output yang sesuai, karena jika tidak ada output dianggap tidak selesai.
- Misal, Anda menggunakan df = df.dropna() silakan gunakan df.isnull().sum() sebagai tanda sudah berhasil. Silakan sesuaikan seluruh output dengan perintah yang sudah disediakan.
- Pastikan Anda melakukan Run All sebelum mengirimkan submission untuk memastikan seluruh cell berjalan dengan baik.
- Pastikan Anda menggunakan variabel df dari awal sampai akhir dan tidak diperbolehkan mengganti nama variabel tersebut.
- Hapus simbol pagar (#) pada kode yang bertipe komentar jika Anda menerapkan kriteria tambahan
- Biarkan simbol pagar (#) jika Anda tidak menerapkan kriteria tambahan
- Pastikan Anda mengerjakan sesuai section yang sudah diberikan tanpa mengubah judul atau header yang disediakan.

# **1. Import Library**
Pada tahap ini, Anda perlu mengimpor beberapa pustaka (library) Python yang dibutuhkan untuk analisis data dan pembangunan model machine learning.

In [23]:
import pandas as pd
import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix
import joblib


# **2. Memuat Dataset dari Hasil Clustering**
Memuat dataset hasil clustering dari file CSV ke dalam variabel DataFrame.

In [7]:
# Gunakan dataset hasil clustering yang memiliki fitur Target
# Silakan gunakan dataset data_clustering jika tidak menerapkan Interpretasi Hasil Clustering [Advanced]
# Silakan gunakan dataset data_clustering_inverse jika menerapkan Interpretasi Hasil Clustering [Advanced]
# Lengkapi kode berikut
# ___ = pd_read_csv("___.csv")

# Jika memakai hasil interpretasi advanced, gunakan data_clustering_inverse.csv
df = pd.read_csv("data_clustering_inverse.csv")

In [38]:
# Tampilkan 5 baris pertama dengan function head.
df.head()

TransactionAmount  TransactionType  Location  Channel  CustomerAge  \
0              14.09                1        36        0         70.0   
1             376.24                1        15        0         68.0   
2             126.29                1        23        2         19.0   
3             184.50                1        33        2         26.0   
4              92.15                1        28        0         18.0   

   CustomerOccupation  TransactionDuration  LoginAttempts  AccountBalance  \
0                   0                 81.0            1.0         5112.21   
1                   0                141.0            1.0        13758.91   
2                   3                 56.0            1.0         1122.35   
3                   3                 25.0            1.0         8569.06   
4                   3                172.0            1.0          781.68   

   CustomerAge_bin  TransactionAmount_bin  Target  
0                2                      0       3  
1                2                      0       2  
2                1                      0       0  
3                1                      0       0  
4                3                      0       0

In [39]:
df.corr()['Target'].sort_values(ascending=False)


Target                   1.000000
Location                 0.345479
Channel                  0.043461
AccountBalance           0.023871
TransactionDuration      0.005405
TransactionAmount        0.005178
TransactionAmount_bin   -0.003076
TransactionType         -0.029379
CustomerAge             -0.045081
CustomerAge_bin         -0.050055
CustomerOccupation      -0.065491
LoginAttempts                 NaN
Name: Target, dtype: float64

# **3. Data Splitting**
Tahap Data Splitting bertujuan untuk memisahkan dataset menjadi dua bagian: data latih (training set) dan data uji (test set).

In [52]:
# Menggunakan train_test_split() untuk melakukan pembagian dataset.
# Pisahkan fitur dan target
X = df.drop(columns=['Target'])
y = df['Target']

# Split data (misal 80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

df.head()

TransactionAmount  TransactionType  Location  Channel  CustomerAge  \
0              14.09                1        36        0         70.0   
1             376.24                1        15        0         68.0   
2             126.29                1        23        2         19.0   
3             184.50                1        33        2         26.0   
4              92.15                1        28        0         18.0   

   CustomerOccupation  TransactionDuration  LoginAttempts  AccountBalance  \
0                   0                 81.0            1.0         5112.21   
1                   0                141.0            1.0        13758.91   
2                   3                 56.0            1.0         1122.35   
3                   3                 25.0            1.0         8569.06   
4                   3                172.0            1.0          781.68   

   CustomerAge_bin  TransactionAmount_bin  Target  
0                2                      0       3  
1                2                      0       2  
2                1                      0       0  
3                1                      0       0  
4                3                      0       0

# **4. Membangun Model Klasifikasi**
Setelah memilih algoritma klasifikasi yang sesuai, langkah selanjutnya adalah melatih model menggunakan data latih.

Berikut adalah rekomendasi tahapannya.
1. Menggunakan algoritma klasifikasi yaitu Decision Tree.
2. Latih model menggunakan data yang sudah dipisah.

In [53]:
# Buatlah model klasifikasi menggunakan Decision Tree
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [54]:
# Menyimpan Model
# import joblib
# joblib.dump(model, 'decision_tree_model.h5')

joblib.dump(dt_model, 'decision_tree_model.h5')

['decision_tree_model.h5']

# **5. Memenuhi Kriteria Skilled dan Advanced dalam Membangun Model Klasifikasi**



**Biarkan kosong jika tidak menerapkan kriteria skilled atau advanced**

In [55]:
# Melatih model menggunakan algoritma klasifikasi scikit-learn selain Decision Tree.
y_pred_dt = dt_model.predict(X_test)

In [56]:
# Menampilkan hasil evaluasi akurasi, presisi, recall, dan F1-Score pada seluruh algoritma yang sudah dibuat.
print("Decision Tree Classification Report:")
print(classification_report(y_test, y_pred_dt))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_dt))

Decision Tree Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       111
           1       1.00      1.00      1.00       117
           2       1.00      1.00      1.00       112
           3       1.00      1.00      1.00        97

    accuracy                           1.00       437
   macro avg       1.00      1.00      1.00       437
weighted avg       1.00      1.00      1.00       437

Confusion Matrix:
 [[111   0   0   0]
 [  0 117   0   0]
 [  0   0 112   0]
 [  0   0   0  97]]


In [57]:
# Menyimpan Model Selain Decision Tree
# Model ini bisa lebih dari satu
# import joblib
# joblib.dump(___, 'explore_<Nama Algoritma>_classification.h5')

# 1. Random Forest Classifier
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)
y_pred_rf = rf_model.predict(X_test)

# Simpan model Random Forest
joblib.dump(rf_model, 'explore_RandomForest_classification.h5')

# 2. Logistic Regression (untuk multi-class classification)
lr_model = LogisticRegression(max_iter=1000, solver='liblinear', random_state=42)
lr_model.fit(X_train, y_train)
y_pred_lr = lr_model.predict(X_test)

# Simpan model Logistic Regression
joblib.dump(lr_model, 'explore_LogReg_classification.h5')

# Evaluasi
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

models = {
    'Random Forest': y_pred_rf,
    'Logistic Regression': y_pred_lr
}
for name, preds in models.items():
    print(f"\n{name} - Accuracy: {accuracy_score(y_test, preds):.4f} | Precision: {precision_score(y_test, preds, average='macro'):.4f} | Recall: {recall_score(y_test, preds, average='macro'):.4f} | F1-Score: {f1_score(y_test, preds, average='macro'):.4f}")


Random Forest - Accuracy: 1.0000 | Precision: 1.0000 | Recall: 1.0000 | F1-Score: 1.0000

Logistic Regression - Accuracy: 0.8307 | Precision: 0.8296 | Recall: 0.8339 | F1-Score: 0.8289


In [58]:
pd.concat([X.head(), y.head()], axis=1)

TransactionAmount  TransactionType  Location  Channel  CustomerAge  \
0              14.09                1        36        0         70.0   
1             376.24                1        15        0         68.0   
2             126.29                1        23        2         19.0   
3             184.50                1        33        2         26.0   
4              92.15                1        28        0         18.0   

   CustomerOccupation  TransactionDuration  LoginAttempts  AccountBalance  \
0                   0                 81.0            1.0         5112.21   
1                   0                141.0            1.0        13758.91   
2                   3                 56.0            1.0         1122.35   
3                   3                 25.0            1.0         8569.06   
4                   3                172.0            1.0          781.68   

   CustomerAge_bin  TransactionAmount_bin  Target  
0                2                      0       3  
1                2                      0       2  
2                1                      0       0  
3                1                      0       0  
4                3                      0       0

Hyperparameter Tuning Model

Pilih salah satu algoritma yang ingin Anda tuning

In [59]:
# Lakukan Hyperparameter Tuning dan Latih ulang.
# Lakukan dalam satu cell ini saja.

# Definisikan grid parameter
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [3, 5, 10, None],
    'min_samples_split': [2, 5, 10]
}

# Inisialisasi model
rf_tune = RandomForestClassifier(random_state=42)

# Grid Search
grid = GridSearchCV(rf_tune, param_grid, cv=3, scoring='f1_macro')
grid.fit(X_train, y_train)


Tuned Random Forest - Accuracy: 1.0000 | Precision: 1.0000 | Recall: 1.0000 | F1-Score: 1.0000


['tuning_classification.h5']

In [61]:
# Menampilkan hasil evaluasi akurasi, presisi, recall, dan F1-Score pada algoritma yang sudah dituning.
# Evaluasi model terbaik
y_pred_tune = grid.best_estimator_.predict(X_test)
print("\nTuned Random Forest - Accuracy: {:.4f} | Precision: {:.4f} | Recall: {:.4f} | F1-Score: {:.4f}".format(
    accuracy_score(y_test, y_pred_tune),
    precision_score(y_test, y_pred_tune, average='macro'),
    recall_score(y_test, y_pred_tune, average='macro'),
    f1_score(y_test, y_pred_tune, average='macro')
))


Tuned Random Forest - Accuracy: 1.0000 | Precision: 1.0000 | Recall: 1.0000 | F1-Score: 1.0000


In [62]:
# Menyimpan Model hasil tuning
# import joblib
# joblib.dump(__, 'tuning_classification.h5')
joblib.dump(grid.best_estimator_, 'tuning_classification.h5')

['tuning_classification.h5']

End of Code